name: 'MicroK8s Action'
description: 'Run a MicroK8s Kubernetes cluster in your GitHub Action'
author: "balchua"
inputs:
  channel:  # MicroK8s channel
    description: 'The MicroK8s Channel to use.  More information here https://microk8s.io/docs/setting-snap-channel'
    required: true
    default: 'latest/stable'
  rbac:
    description: "Enable Kubernetes RBAC."
    required: true
    default: "false"
  dns:
    description: "Enable coredns."
    required: true
    default: "false"
  storage:
    description: "Enable storage"
    required: true
    default: "false"
  addons:
    description: "A JSON array of addons to enable"    
    required: false
    default: |-
      []

runs:
  using: 'node12'
  main: 'lib/index.js'