name: Test Microk8s with optional addons
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to install MicroK8s
    steps:
    - uses: balchua/microk8s-actions@feature/addons
      with:
        channel: '1.19/stable'
        storage: 'true'
    - name: Test MicroK8s
      id: microk8s
      run: |
        set -ex
        kubectl get no
        kubectl get pods -A -o wide

        sleep 20s

        # wait for storage pod to be ready
        kubectl -n kube-system wait --for=condition=ready pod -l k8s-app=hostpath-provisioner --timeout=60s
        storage_ready=$?

        if [ $storage_ready -ne 0 ]; then
          echo "Error storage not ready."
          exit $storage_ready
        fi
        