name: Test Microk8s
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to install MicroK8s
    steps:
    - uses: balchua/microk8s-actions@v0.1
      with:
        channel: '1.18/stable'
        rbac: 'true'
        dns: 'true'
    - name: Test MicroK8s
      id: microk8s
      run: |
        kubectl get no
        kubectl get pods -A
        sleep 20s
        kubectl get pods -A -o wide
        