name: Test Microk8s
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to install MicroK8s
    steps:
    - uses: balchua/microk8s-actions@master
      with:
        channel: 'latest/stable'    
    - name: Test MicroK8s
      id: microk8s
      run: |
        which kubectl
        kubectl get no
        