name: Test Microk8s
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to install MicroK8s
    steps:
    - uses: balchua/microk8s-actions@master
      with:
        channel: '1.26/stable'
        addons: '["rbac", "dns", "hostpath-storage", "registry"]'
    - name: Check User
      run: |
        id
        sg microk8s -c 'microk8s status'
    - uses: docker/setup-qemu-action@v2 
      name: Set up docker
    - name: Test MicroK8s
      id: microk8s
      run: |
        set -ex
        kubectl get no
        kubectl get pods -A -o wide
        sleep 120 # Give it sometime before we start checking for pod readiness.
        # wait for storage pod to be ready
        kubectl -n kube-system wait --for=condition=ready pod -l k8s-app=hostpath-provisioner --timeout=60s
        storage_ready=$?

        if [ $storage_ready -ne 0 ]; then
          echo "Error storage not ready."
          exit $storage_ready
        fi
    - name: Test MicroK8s commands
      id: microk8s-commands
      run: |
        set -ex
        echo "Executing microk8s status using sg command."
        sg microk8s -c 'microk8s status'
        echo "Executing microk8s status using sudo command."
        sudo microk8s status
    - name: Docker pull and push to local "registry"
      run: |
        docker pull balchu/bopbag:1.0.1
        REGISTRY_IP=`kubectl -n container-registry get svc/registry -o jsonpath='{.spec.clusterIP}'`
        echo $REGISTRY_IP
        docker tag balchu/bopbag:1.0.1 $REGISTRY_IP:5000/balchu/bopbag:1.0.1
        docker push $REGISTRY_IP:5000/balchu/bopbag:1.0.1
        curl http://$REGISTRY_IP:5000/v2/_catalog
        
