name: Test push image to local registry
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to install MicroK8s
    steps:
    - uses: balchua/microk8s-actions@master
      with:
        channel: '1.26/stable'
        addons: '["rbac", "dns", "hostpath-storage", "registry"]'
    - name: Check User
      run: |
        id
        sg microk8s -c 'microk8s status'

    - name: Docker pull and push to local "registry"
      run: |
        docker pull busybox:latest
        REGISTRY_IP=`kubectl -n container-registry get svc/registry -o jsonpath='{.spec.clusterIP}'`
        echo $REGISTRY_IP
        docker tag busybox:latest localhost:32000/my-repo/busybox:latest
        docker push localhost:32000/my-repo/busybox:latest
        curl http://localhost:32000/v2/_catalog
        
