name: Test Microk8s with non existent channel
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to install MicroK8s
    steps:
    - uses: balchua/microk8s-actions@master
      with:
        channel: 'nonexistent'
        addons: '["storage"]'
    - name: Test MicroK8s
      id: microk8s
      run: id
        